version: '3.4'

services:
  rocketchat:
    image: rocket.chat:5
    container_name: rocketchat-www
    restart: on-failure
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://rocketchat-db:27017/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://rocketchat-db:27017/local?replicaSet=rs0&directConnection=true
      - DEPLOY_METHOD=docker
    depends_on:
      - mongo
    networks:
      - internal
    ports:
      - 3000:3000

  mongo:
    image: mongo:4.4
    container_name: rocketchat-db
    restart: on-failure
    volumes:
     - ./data/db:/data/db
     - ./data/dump:/dump
    command: mongod --dbpath /data/db --oplogSize 128 --replSet rs0 --storageEngine wiredTiger
    networks:
      - internal

  mongo-init-replica:
    image: mongo:4.4
    command: 'bash -c "for i in `seq 1 30`; do mongo rocketchat-db/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i t imes. Waiting 5 secs.
..\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - mongo
    networks:
      - internal

networks:
    internal:
        name: internal
        external: false

